services:
  app:
    build:
      context: .

    container_name: dmdcare-app
    restart: unless-stopped

    ports:
      - "8001:80"

    volumes:
      - .:/var/www/html

    networks:
      - dev-network

networks:
  dev-network:
    external: true