-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Aug 24, 2026 at 10:59 AM
-- Server version: 8.3.0
-- PHP Version: 8.1.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dmd_care_bangladesh`
--

-- --------------------------------------------------------

--
-- Table structure for table `content_items`
--

DROP TABLE IF EXISTS `content_items`;
CREATE TABLE IF NOT EXISTS `content_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(220) COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci,
  `body` text COLLATE utf8mb4_unicode_ci,
  `image_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `position` int NOT NULL,
  `is_published` tinyint(1) NOT NULL,
  `extra` json NOT NULL,
  `created_by_id` int DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `created_by_id` (`created_by_id`),
  KEY `ix_content_items_slug` (`slug`),
  KEY `ix_content_items_id` (`id`),
  KEY `ix_content_items_type` (`type`)
) ENGINE=MyISAM AUTO_INCREMENT=79 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `content_items`
--

INSERT INTO `content_items` (`id`, `type`, `title`, `slug`, `summary`, `body`, `image_url`, `position`, `is_published`, `extra`, `created_by_id`, `created_at`, `updated_at`) VALUES
(1, 'health_team', 'Dr. Husnea Ara Khan', 'dr-husnea-ara-khan', 'Paediatric Neurologist', 'MBBS, FCPS (Paediatrics), FCPS (Paediatric Neurology & Development)\nAssistant Professor, Department of Paediatric Neurology National Institute of Neurosciences & Hospital (NINS&H), Dhaka', 'assets/src/img/Dr. Husnea Ara Khan.webp', 1, 1, '{\"workplace\": \"\", \"job_position\": \"Assistant Professor, Department of Paediatric Neurology National Institute of Neurosciences & Hospital (NINS&H), Dhaka\", \"qualifications\": \"MBBS, FCPS (Paediatrics), FCPS (Paediatric Neurology & Development)\"}', 1, '2026-08-10 07:21:03', '2026-08-12 18:17:44'),
(2, 'health_team', 'Dr. Jobaida Parvin', 'dr-jobaida-parvin', 'Paediatric Neurologist', 'MBBS, FCPS (Child Neurology)\nAssistant Professor, Department of Paediatric Neurology National Institute of Neurosciences & Hospital (NINS&H), Dhaka', 'assets/src/img/Dr. Jobaida Parvin.webp', 2, 1, '{}', 1, '2026-08-10 07:21:03', '2026-08-10 07:21:03'),
(3, 'health_team', 'Dr. Shaoli Sarker', 'dr-shaoli-sarker', 'Paediatric Neurologist', 'MBBS (SSMC), FCPS (Paediatrics)\nAssociate Professor, Department of Paediatric Neuroscience, Bangladesh Shishu (Children) Hospital & Institute, Dhaka', 'assets/src/img/Dr. Shaoli Sarker.webp', 3, 1, '{}', 1, '2026-08-10 07:21:03', '2026-08-10 07:21:03'),
(4, 'gallery', 'DMD clinic opening', 'dmd-clinic-opening', 'Neuro muscular clinic opening', NULL, '/uploads/20260810212328165264_657246684_935684902710507_1011691135864960188_n.jpg', 1, 1, '{\"media_type\": \"photo\"}', 1, '2026-08-10 07:21:03', '2026-08-10 21:23:28'),
(5, 'gallery', 'Patients with doctors', 'patients-with-doctors', 'DMD patients and doctors together', NULL, 'assets/src/img/photo_2.webp', 2, 1, '{}', 1, '2026-08-10 07:21:03', '2026-08-10 07:21:03'),
(6, 'patient_story', 'Muntasir Billah', 'muntasir-billah', 'Wheelchair user', 'Muntasir Billah is living with Duchenne Muscular Dystrophy and continues treatment, care, and family-supported rehabilitation.', 'assets/src/img/p_muntasir_billah.jpg', 1, 1, '{\"age\": \"Diagnosed at 12 years\", \"phone\": \"\", \"author\": \"Muntasir Billah\", \"status\": \"Wheelchair user\", \"facebook\": \"\", \"whatsapp\": \"\", \"home_text\": \"fcutc\", \"detail_body\": \"Muntasir Billah is living with Duchenne Muscular Dystrophy and continues treatment, care, and family-supported rehabilitation.\", \"detail_title\": \"Muntasir Billah\", \"diagnosis_year\": \"2022\", \"home_link_text\": \"Click for more stories about me\", \"detail_video_url\": \"\"}', 1, '2026-08-10 07:21:03', '2026-08-22 10:13:26'),
(12, 'gallery', 'DMD clinic opening', 'dmd-clinic-opening', 'afwafawas', NULL, '/uploads/20260810212400275591_657246684_935684902710507_1011691135864960188_n.jpg', 3, 1, '{\"media_type\": \"photo\"}', 1, '2026-08-10 21:24:00', '2026-08-10 21:24:00'),
(13, 'gallery', 'Duchenne Muscular Dystrophy (DMD) – কারণ, লক্ষণ, চিকিৎসা ও প্যাথোলজি', 'duchenne-muscular-dystrophy-dmd', 'Duchenne Muscular Dystrophy (DMD) – কারণ, লক্ষণ, চিকিৎসা ও প্যাথোলজি', 'https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT', NULL, 4, 1, '{\"video_url\": \"https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(14, 'gallery', 'Duchenne muscular dystrophys সম্পর্কে জানা প্রয়োজন', 'duchenne-muscular-dystrophys', 'Duchenne muscular dystrophys সম্পর্কে জানা প্রয়োজন', 'https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk', NULL, 5, 1, '{\"video_url\": \"https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(15, 'gallery', 'DMD - পরীক্ষা ও ফলাফল', 'dmd', 'DMD - পরীক্ষা ও ফলাফল', 'https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7', NULL, 6, 1, '{\"video_url\": \"https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(16, 'gallery', 'DMD-এর প্রাকৃতিক ইতিহাস', 'dmd', 'DMD-এর প্রাকৃতিক ইতিহাস', 'https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr', NULL, 7, 1, '{\"video_url\": \"https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(17, 'gallery', 'ইতিহাস কীভাবে DMD নির্ণয়ে সাহায্য করতে পারে', 'dmd', 'ইতিহাস কীভাবে DMD নির্ণয়ে সাহায্য করতে পারে', 'https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ', NULL, 8, 1, '{\"video_url\": \"https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(18, 'gallery', 'প্রাথমিক নির্ণয় ও চিকিৎসা উন্নত করতে সচেতনতা বৃদ্ধি', 'item-1786375645', 'প্রাথমিক নির্ণয় ও চিকিৎসা উন্নত করতে সচেতনতা বৃদ্ধি', 'https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g', NULL, 9, 1, '{\"video_url\": \"https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g\", \"media_type\": \"video\"}', NULL, '2026-08-10 21:27:02', '2026-08-10 21:27:26'),
(19, 'patient_story', 'Demo Patient 01 - Ayaan Rahman', 'demo-patient-story-01', 'Under physiotherapy care', 'This is a demonstration patient story for Ayaan Rahman, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_1.jpg', 2, 1, '{\"age\": \"Diagnosed at 6 years\", \"author\": \"Demo Patient 01 - Ayaan Rahman\", \"status\": \"Under physiotherapy care\", \"home_text\": \"This is a demonstration patient story for Ayaan Rahman, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Ayaan Rahman, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 01 - Ayaan Rahman\", \"diagnosis_year\": \"2016\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(20, 'patient_story', 'Demo Patient 02 - Nabil Hasan', 'demo-patient-story-02', 'Can walk with support', 'This is a demonstration patient story for Nabil Hasan, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_2.jpg', 3, 1, '{\"age\": \"Diagnosed at 7 years\", \"author\": \"Demo Patient 02 - Nabil Hasan\", \"status\": \"Can walk with support\", \"home_text\": \"This is a demonstration patient story for Nabil Hasan, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Nabil Hasan, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 02 - Nabil Hasan\", \"diagnosis_year\": \"2017\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(21, 'patient_story', 'Demo Patient 03 - Rafi Ahmed', 'demo-patient-story-03', 'Wheelchair user', 'This is a demonstration patient story for Rafi Ahmed, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_3.jpg', 4, 1, '{\"age\": \"Diagnosed at 8 years\", \"author\": \"Demo Patient 03 - Rafi Ahmed\", \"status\": \"Wheelchair user\", \"home_text\": \"This is a demonstration patient story for Rafi Ahmed, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Rafi Ahmed, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 03 - Rafi Ahmed\", \"diagnosis_year\": \"2018\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(22, 'patient_story', 'Demo Patient 04 - Samiul Islam', 'demo-patient-story-04', 'Receiving multidisciplinary care', 'This is a demonstration patient story for Samiul Islam, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/p_muntasir_billah.jpg', 5, 1, '{\"age\": \"Diagnosed at 9 years\", \"author\": \"Demo Patient 04 - Samiul Islam\", \"status\": \"Receiving multidisciplinary care\", \"home_text\": \"This is a demonstration patient story for Samiul Islam, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Samiul Islam, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 04 - Samiul Islam\", \"diagnosis_year\": \"2019\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(23, 'patient_story', 'Demo Patient 05 - Zayan Karim', 'demo-patient-story-05', 'Under physiotherapy care', 'This is a demonstration patient story for Zayan Karim, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_1.jpg', 6, 1, '{\"age\": \"Diagnosed at 10 years\", \"author\": \"Demo Patient 05 - Zayan Karim\", \"status\": \"Under physiotherapy care\", \"home_text\": \"This is a demonstration patient story for Zayan Karim, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Zayan Karim, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 05 - Zayan Karim\", \"diagnosis_year\": \"2020\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(24, 'patient_story', 'Demo Patient 06 - Tahmid Hossain', 'demo-patient-story-06', 'Can walk with support', 'This is a demonstration patient story for Tahmid Hossain, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_2.jpg', 7, 1, '{\"age\": \"Diagnosed at 11 years\", \"author\": \"Demo Patient 06 - Tahmid Hossain\", \"status\": \"Can walk with support\", \"home_text\": \"This is a demonstration patient story for Tahmid Hossain, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Tahmid Hossain, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 06 - Tahmid Hossain\", \"diagnosis_year\": \"2021\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(25, 'patient_story', 'Demo Patient 07 - Rayyan Kabir', 'demo-patient-story-07', 'Wheelchair user', 'This is a demonstration patient story for Rayyan Kabir, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_3.jpg', 8, 1, '{\"age\": \"Diagnosed at 12 years\", \"author\": \"Demo Patient 07 - Rayyan Kabir\", \"status\": \"Wheelchair user\", \"home_text\": \"This is a demonstration patient story for Rayyan Kabir, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Rayyan Kabir, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 07 - Rayyan Kabir\", \"diagnosis_year\": \"2022\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(26, 'patient_story', 'Demo Patient 08 - Farhan Chowdhury', 'demo-patient-story-08', 'Receiving multidisciplinary care', 'This is a demonstration patient story for Farhan Chowdhury, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/p_muntasir_billah.jpg', 9, 1, '{\"age\": \"Diagnosed at 13 years\", \"author\": \"Demo Patient 08 - Farhan Chowdhury\", \"status\": \"Receiving multidisciplinary care\", \"home_text\": \"This is a demonstration patient story for Farhan Chowdhury, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Farhan Chowdhury, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 08 - Farhan Chowdhury\", \"diagnosis_year\": \"2023\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(27, 'patient_story', 'Demo Patient 09 - Adnan Mahmud', 'demo-patient-story-09', 'Under physiotherapy care', 'This is a demonstration patient story for Adnan Mahmud, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_1.jpg', 10, 1, '{\"age\": \"Diagnosed at 5 years\", \"author\": \"Demo Patient 09 - Adnan Mahmud\", \"status\": \"Under physiotherapy care\", \"home_text\": \"This is a demonstration patient story for Adnan Mahmud, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Adnan Mahmud, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 09 - Adnan Mahmud\", \"diagnosis_year\": \"2024\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(28, 'patient_story', 'Demo Patient 10 - Ibrahim Khan', 'demo-patient-story-10', 'Can walk with support', 'This is a demonstration patient story for Ibrahim Khan, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_2.jpg', 11, 1, '{\"age\": \"Diagnosed at 6 years\", \"author\": \"Demo Patient 10 - Ibrahim Khan\", \"status\": \"Can walk with support\", \"home_text\": \"This is a demonstration patient story for Ibrahim Khan, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Ibrahim Khan, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 10 - Ibrahim Khan\", \"diagnosis_year\": \"2015\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(29, 'patient_story', 'Demo Patient 11 - Arham Siddique', 'demo-patient-story-11', 'Wheelchair user', 'This is a demonstration patient story for Arham Siddique, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_3.jpg', 12, 1, '{\"age\": \"Diagnosed at 7 years\", \"author\": \"Demo Patient 11 - Arham Siddique\", \"status\": \"Wheelchair user\", \"home_text\": \"This is a demonstration patient story for Arham Siddique, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Arham Siddique, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 11 - Arham Siddique\", \"diagnosis_year\": \"2016\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(30, 'patient_story', 'Demo Patient 12 - Fahim Rahman', 'demo-patient-story-12', 'Receiving multidisciplinary care', 'This is a demonstration patient story for Fahim Rahman, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/p_muntasir_billah.jpg', 13, 1, '{\"age\": \"Diagnosed at 8 years\", \"author\": \"Demo Patient 12 - Fahim Rahman\", \"status\": \"Receiving multidisciplinary care\", \"home_text\": \"This is a demonstration patient story for Fahim Rahman, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Fahim Rahman, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 12 - Fahim Rahman\", \"diagnosis_year\": \"2017\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(31, 'patient_story', 'Demo Patient 13 - Mahin Ahmed', 'demo-patient-story-13', 'Under physiotherapy care', 'This is a demonstration patient story for Mahin Ahmed, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_1.jpg', 14, 1, '{\"age\": \"Diagnosed at 9 years\", \"author\": \"Demo Patient 13 - Mahin Ahmed\", \"status\": \"Under physiotherapy care\", \"home_text\": \"This is a demonstration patient story for Mahin Ahmed, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Mahin Ahmed, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 13 - Mahin Ahmed\", \"diagnosis_year\": \"2018\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(32, 'patient_story', 'Demo Patient 14 - Nafis Hasan', 'demo-patient-story-14', 'Can walk with support', 'This is a demonstration patient story for Nafis Hasan, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_2.jpg', 15, 1, '{\"age\": \"Diagnosed at 10 years\", \"author\": \"Demo Patient 14 - Nafis Hasan\", \"status\": \"Can walk with support\", \"home_text\": \"This is a demonstration patient story for Nafis Hasan, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Nafis Hasan, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 14 - Nafis Hasan\", \"diagnosis_year\": \"2019\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(33, 'patient_story', 'Demo Patient 15 - Rayan Islam', 'demo-patient-story-15', 'Wheelchair user', 'This is a demonstration patient story for Rayan Islam, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_3.jpg', 16, 1, '{\"age\": \"Diagnosed at 11 years\", \"author\": \"Demo Patient 15 - Rayan Islam\", \"status\": \"Wheelchair user\", \"home_text\": \"This is a demonstration patient story for Rayan Islam, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Rayan Islam, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 15 - Rayan Islam\", \"diagnosis_year\": \"2020\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(34, 'patient_story', 'Demo Patient 16 - Shafin Karim', 'demo-patient-story-16', 'Receiving multidisciplinary care', 'This is a demonstration patient story for Shafin Karim, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/p_muntasir_billah.jpg', 17, 1, '{\"age\": \"Diagnosed at 12 years\", \"author\": \"Demo Patient 16 - Shafin Karim\", \"status\": \"Receiving multidisciplinary care\", \"home_text\": \"This is a demonstration patient story for Shafin Karim, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Shafin Karim, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 16 - Shafin Karim\", \"diagnosis_year\": \"2021\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(35, 'patient_story', 'Demo Patient 17 - Tanvir Hossain', 'demo-patient-story-17', 'Under physiotherapy care', 'This is a demonstration patient story for Tanvir Hossain, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_1.jpg', 18, 1, '{\"age\": \"Diagnosed at 13 years\", \"author\": \"Demo Patient 17 - Tanvir Hossain\", \"status\": \"Under physiotherapy care\", \"home_text\": \"This is a demonstration patient story for Tanvir Hossain, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Tanvir Hossain, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 17 - Tanvir Hossain\", \"diagnosis_year\": \"2022\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(36, 'patient_story', 'Demo Patient 18 - Zubair Kabir', 'demo-patient-story-18', 'Can walk with support', 'This is a demonstration patient story for Zubair Kabir, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_2.jpg', 19, 1, '{\"age\": \"Diagnosed at 5 years\", \"author\": \"Demo Patient 18 - Zubair Kabir\", \"status\": \"Can walk with support\", \"home_text\": \"This is a demonstration patient story for Zubair Kabir, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Zubair Kabir, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 18 - Zubair Kabir\", \"diagnosis_year\": \"2023\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(37, 'patient_story', 'Demo Patient 19 - Arian Mahmud', 'demo-patient-story-19', 'Wheelchair user', 'This is a demonstration patient story for Arian Mahmud, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/patients_3.jpg', 20, 1, '{\"age\": \"Diagnosed at 6 years\", \"author\": \"Demo Patient 19 - Arian Mahmud\", \"status\": \"Wheelchair user\", \"home_text\": \"This is a demonstration patient story for Arian Mahmud, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Arian Mahmud, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 19 - Arian Mahmud\", \"diagnosis_year\": \"2024\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(38, 'patient_story', 'Demo Patient 20 - Sakib Khan', 'demo-patient-story-20', 'Receiving multidisciplinary care', 'This is a demonstration patient story for Sakib Khan, created to preview the patient-stories listing and pagination layout.', 'assets/src/img/p_muntasir_billah.jpg', 21, 1, '{\"age\": \"Diagnosed at 7 years\", \"author\": \"Demo Patient 20 - Sakib Khan\", \"status\": \"Receiving multidisciplinary care\", \"home_text\": \"This is a demonstration patient story for Sakib Khan, created to preview the patient-stories listing and pagination layout.\", \"detail_body\": \"This is a demonstration patient story for Sakib Khan, created to preview the patient-stories listing and pagination layout.\", \"detail_title\": \"Demo Patient 20 - Sakib Khan\", \"diagnosis_year\": \"2015\", \"home_link_text\": \"Read this demo story\"}', 1, '2026-08-18 10:47:43', '2026-08-18 10:47:43'),
(39, 'gallery', 'Demo Gallery Photo 01', 'demo-gallery-photo-01', 'Demonstration photo 01 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_0.webp', 10, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(40, 'gallery', 'Demo Gallery Photo 02', 'demo-gallery-photo-02', 'Demonstration photo 02 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_1.webp', 11, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(41, 'gallery', 'Demo Gallery Photo 03', 'demo-gallery-photo-03', 'Demonstration photo 03 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_2.webp', 12, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(42, 'gallery', 'Demo Gallery Photo 04', 'demo-gallery-photo-04', 'Demonstration photo 04 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_3.webp', 13, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(43, 'gallery', 'Demo Gallery Photo 05', 'demo-gallery-photo-05', 'Demonstration photo 05 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_4.webp', 14, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(44, 'gallery', 'Demo Gallery Photo 06', 'demo-gallery-photo-06', 'Demonstration photo 06 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_5.webp', 15, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(45, 'gallery', 'Demo Gallery Photo 07', 'demo-gallery-photo-07', 'Demonstration photo 07 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_6.webp', 16, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(46, 'gallery', 'Demo Gallery Photo 08', 'demo-gallery-photo-08', 'Demonstration photo 08 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_7.webp', 17, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(47, 'gallery', 'Demo Gallery Photo 09', 'demo-gallery-photo-09', 'Demonstration photo 09 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_0.webp', 18, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(48, 'gallery', 'Demo Gallery Photo 10', 'demo-gallery-photo-10', 'Demonstration photo 10 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_1.webp', 19, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(49, 'gallery', 'Demo Gallery Photo 11', 'demo-gallery-photo-11', 'Demonstration photo 11 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_2.webp', 20, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(50, 'gallery', 'Demo Gallery Photo 12', 'demo-gallery-photo-12', 'Demonstration photo 12 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_3.webp', 21, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(51, 'gallery', 'Demo Gallery Photo 13', 'demo-gallery-photo-13', 'Demonstration photo 13 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_4.webp', 22, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(52, 'gallery', 'Demo Gallery Photo 14', 'demo-gallery-photo-14', 'Demonstration photo 14 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_5.webp', 23, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(53, 'gallery', 'Demo Gallery Photo 15', 'demo-gallery-photo-15', 'Demonstration photo 15 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_6.webp', 24, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(54, 'gallery', 'Demo Gallery Photo 16', 'demo-gallery-photo-16', 'Demonstration photo 16 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_7.webp', 25, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(55, 'gallery', 'Demo Gallery Photo 17', 'demo-gallery-photo-17', 'Demonstration photo 17 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_0.webp', 26, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(56, 'gallery', 'Demo Gallery Photo 18', 'demo-gallery-photo-18', 'Demonstration photo 18 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_1.webp', 27, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(57, 'gallery', 'Demo Gallery Photo 19', 'demo-gallery-photo-19', 'Demonstration photo 19 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_2.webp', 28, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(58, 'gallery', 'Demo Gallery Photo 20', 'demo-gallery-photo-20', 'Demonstration photo 20 for the DMD Care Bangladesh gallery.', NULL, 'assets/src/img/photo_3.webp', 29, 1, '{\"demo\": true, \"media_type\": \"photo\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(59, 'gallery', 'Demo Gallery Video 01', 'demo-gallery-video-01', 'Demonstration video 01 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT', NULL, 30, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(60, 'gallery', 'Demo Gallery Video 02', 'demo-gallery-video-02', 'Demonstration video 02 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk', NULL, 31, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(61, 'gallery', 'Demo Gallery Video 03', 'demo-gallery-video-03', 'Demonstration video 03 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7', NULL, 32, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(62, 'gallery', 'Demo Gallery Video 04', 'demo-gallery-video-04', 'Demonstration video 04 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr', NULL, 33, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(63, 'gallery', 'Demo Gallery Video 05', 'demo-gallery-video-05', 'Demonstration video 05 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ', NULL, 34, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(64, 'gallery', 'Demo Gallery Video 06', 'demo-gallery-video-06', 'Demonstration video 06 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g', NULL, 35, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(65, 'gallery', 'Demo Gallery Video 07', 'demo-gallery-video-07', 'Demonstration video 07 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT', NULL, 36, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(66, 'gallery', 'Demo Gallery Video 08', 'demo-gallery-video-08', 'Demonstration video 08 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk', NULL, 37, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(67, 'gallery', 'Demo Gallery Video 09', 'demo-gallery-video-09', 'Demonstration video 09 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7', NULL, 38, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(68, 'gallery', 'Demo Gallery Video 10', 'demo-gallery-video-10', 'Demonstration video 10 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr', NULL, 39, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(69, 'gallery', 'Demo Gallery Video 11', 'demo-gallery-video-11', 'Demonstration video 11 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ', NULL, 40, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(70, 'gallery', 'Demo Gallery Video 12', 'demo-gallery-video-12', 'Demonstration video 12 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g', NULL, 41, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(71, 'gallery', 'Demo Gallery Video 13', 'demo-gallery-video-13', 'Demonstration video 13 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT', NULL, 42, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(72, 'gallery', 'Demo Gallery Video 14', 'demo-gallery-video-14', 'Demonstration video 14 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk', NULL, 43, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(73, 'gallery', 'Demo Gallery Video 15', 'demo-gallery-video-15', 'Demonstration video 15 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7', NULL, 44, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/fU6NF5XnzSE?si=5MbEwlybw_pjmFv7\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(74, 'gallery', 'Demo Gallery Video 16', 'demo-gallery-video-16', 'Demonstration video 16 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr', NULL, 45, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/sZa0W-GFXWQ?si=r8pYp7zYoqTqOIDr\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(75, 'gallery', 'Demo Gallery Video 17', 'demo-gallery-video-17', 'Demonstration video 17 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ', NULL, 46, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/2DlekUcnsuQ?si=dHCQYw6dC1qbj8PQ\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(76, 'gallery', 'Demo Gallery Video 18', 'demo-gallery-video-18', 'Demonstration video 18 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g', NULL, 47, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/-NTkg1ioqBs?si=qHX1ZQu3_OZSpA5g\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(77, 'gallery', 'Demo Gallery Video 19', 'demo-gallery-video-19', 'Demonstration video 19 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT', NULL, 48, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/Ebu8W8Osuxk?si=NV-f_KarLbu6tbHT\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47'),
(78, 'gallery', 'Demo Gallery Video 20', 'demo-gallery-video-20', 'Demonstration video 20 for the DMD Care Bangladesh gallery.', 'https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk', NULL, 49, 1, '{\"demo\": true, \"video_url\": \"https://www.youtube.com/embed/7EHdCQn6M4Y?si=U57okA1ErGd3_DZk\", \"media_type\": \"video\"}', 1, '2026-08-18 10:54:47', '2026-08-18 10:54:47');

-- --------------------------------------------------------

--
-- Table structure for table `registrations`
--

DROP TABLE IF EXISTS `registrations`;
CREATE TABLE IF NOT EXISTS `registrations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_name` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `guardian_phone` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `guardian_email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `payload` json NOT NULL,
  `created_by_id` int DEFAULT NULL,
  `reviewed_by_id` int DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `created_by_id` (`created_by_id`),
  KEY `reviewed_by_id` (`reviewed_by_id`),
  KEY `ix_registrations_id` (`id`),
  KEY `ix_registrations_status` (`status`),
  KEY `ix_registrations_guardian_phone` (`guardian_phone`),
  KEY `ix_registrations_patient_name` (`patient_name`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `registrations`
--

INSERT INTO `registrations` (`id`, `patient_name`, `guardian_phone`, `guardian_email`, `status`, `source`, `notes`, `payload`, `created_by_id`, `reviewed_by_id`, `created_at`, `updated_at`) VALUES
(1, 'Demo Patient - Arif Hasan', '+8801711000001', 'demo.arif@example.com', 'accepted', 'public', 'Complete demo registration containing every field from the public registration form. Not a real patient.', '{\"age\": \"10\", \"nid\": \"Not applicable\", \"demo\": true, \"nid_2\": \"DEMO-FNID-0001\", \"nid_3\": \"DEMO-MNID-0001\", \"access\": \"Yes\", \"gender\": \"Male\", \"report\": \"Yes\", \"ability\": \"Walks independently\", \"consent\": \"Yes\", \"devices\": \"Ankle Braces\", \"gentest\": \"Yes\", \"housing\": \"Rented\", \"steroid\": \"Yes\", \"therapy\": \"Physiotherapy\", \"liv_area\": \"Urban\", \"mutation\": \"Exon Deletion\", \"insurance\": \"No\", \"contact_no\": \"+8801711000001\", \"occupation\": \"Teacher\", \"res_report\": \"No\", \"attachments\": {\"photo\": {\"url\": \"/uploads/20260818101835706586_ChatGPT_Image_Aug_8_2026_04_14_00_PM.png\", \"filename\": \"ChatGPT Image Aug 8, 2026, 04_14_00 PM.png\", \"content_type\": \"image/png\"}, \"genetic_report\": {\"url\": \"/uploads/20260818101835706586_logo-1768301378.png\", \"filename\": \"logo-1768301378.png\", \"content_type\": \"image/png\"}}, \"blood_group\": \"B+\", \"cardiac_eva\": \"Yes\", \"class_lavel\": \"Class 4\", \"fin_support\": \"Treatment\", \"gene_report\": \"Yes\", \"nationality\": \"Bangladeshi\", \"steroid_use\": \"Deflazacort\", \"fathers_name\": \"Kamal Hasan\", \"mothers_name\": \"Farzana Begum\", \"occupation_2\": \"Homemaker\", \"otherdetails\": \"\", \"breath_report\": \"No\", \"date_of_birth\": \"2016-03-12\", \"email_address\": \"demo.arif@example.com\", \"cardiac_report\": \"No\", \"diagnosis_type\": \"1\", \"otherdetails_2\": \"\", \"present_address\": \"Demo Road 1, Dhaka, Bangladesh\", \"age_at_diagnosis\": \"6\", \"date_of_diagnosis\": \"2022-04-18\", \"fathers_education\": \"Graduate\", \"hobbies_interests\": \"Drawing and cricket\", \"mothers_education\": \"HSC\", \"patient_full_name\": \"Demo Patient - Arif Hasan\", \"permanent_address\": \"Demo Village 1, Dhaka, Bangladesh\", \"current_medications\": \"Deflazacort, calcium and vitamin D\", \"other_health_issues\": \"Mild muscle weakness and fatigue\", \"birth_certificate_no\": \"DEMO-BC-2026-0001\", \"emergency_contact_no\": \"+8801811000001\", \"emotional_challenges\": \"Occasional anxiety related to mobility limitations\", \"total_family_members\": \"4\", \"family_history_of_dmd\": \"No known family history\", \"monthly_family_income\": \"35000 BDT\", \"duration_of_steroid_use\": \"1 years\", \"age_when_steroid_started\": \"7\", \"inclusive_education_support\": \"School accessibility and flexible attendance support\", \"guardian_relation_with_patient\": \"Father\", \"financial_challenges_related_to_treatment\": \"Regular medicine, therapy, travel, and clinical-test costs\"}', NULL, 1, '2026-08-16 18:02:08', '2026-08-18 10:18:36'),
(2, 'Demo Patient - Nabil Ahmed', '+8801711000002', 'demo.nabil@example.com', 'accepted', 'public', 'Complete demo registration containing every field from the public registration form. Not a real patient.', '{\"age\": \"12\", \"nid\": \"Not applicable\", \"demo\": true, \"nid_2\": \"DEMO-FNID-0002\", \"nid_3\": \"DEMO-MNID-0002\", \"access\": \"Yes\", \"gender\": \"Male\", \"report\": \"Yes\", \"ability\": \"Uses wheelchair\", \"consent\": \"Yes\", \"devices\": \"Wheelchair\", \"gentest\": \"Yes\", \"housing\": \"Own\", \"steroid\": \"Yes\", \"therapy\": \"Occupational therapy\", \"liv_area\": \"Semi-urban\", \"mutation\": \"Duplication\", \"insurance\": \"No\", \"contact_no\": \"+8801711000002\", \"occupation\": \"Business\", \"res_report\": \"Yes\", \"attachments\": {\"photo\": {\"url\": \"assets/src/img/patients_2.jpg\", \"demo\": true, \"filename\": \"demo-patient-2.jpg\", \"content_type\": \"image/jpeg\"}, \"genetic_report\": {\"url\": \"assets/src/doc/Treatment-Fact-Sheet-DMD.pdf\", \"demo\": true, \"filename\": \"demo-genetic-report-2.pdf\", \"content_type\": \"application/pdf\"}}, \"blood_group\": \"A+\", \"cardiac_eva\": \"Yes\", \"class_lavel\": \"Class 5\", \"fin_support\": \"Physiotherapy\", \"gene_report\": \"Yes\", \"nationality\": \"Bangladeshi\", \"steroid_use\": \"Deflazacort\", \"fathers_name\": \"Rashed Ahmed\", \"mothers_name\": \"Nusrat Ahmed\", \"occupation_2\": \"Homemaker\", \"otherdetails\": \"\", \"breath_report\": \"No\", \"date_of_birth\": \"2014-07-21\", \"email_address\": \"demo.nabil@example.com\", \"cardiac_report\": \"Yes\", \"diagnosis_type\": \"1\", \"otherdetails_2\": \"\", \"present_address\": \"Demo Road 2, Chattogram, Bangladesh\", \"age_at_diagnosis\": \"7\", \"date_of_diagnosis\": \"2021-09-10\", \"fathers_education\": \"HSC\", \"hobbies_interests\": \"Music and reading\", \"mothers_education\": \"Graduate\", \"patient_full_name\": \"Demo Patient - Nabil Ahmed\", \"permanent_address\": \"Demo Village 2, Chattogram, Bangladesh\", \"current_medications\": \"Deflazacort, calcium and vitamin D\", \"other_health_issues\": \"Mild muscle weakness and fatigue\", \"birth_certificate_no\": \"DEMO-BC-2026-0002\", \"emergency_contact_no\": \"+8801811000002\", \"emotional_challenges\": \"Occasional anxiety related to mobility limitations\", \"total_family_members\": \"5\", \"family_history_of_dmd\": \"No known family history\", \"monthly_family_income\": \"42000 BDT\", \"duration_of_steroid_use\": \"2 years\", \"age_when_steroid_started\": \"8\", \"inclusive_education_support\": \"School accessibility and flexible attendance support\", \"guardian_relation_with_patient\": \"Father\", \"financial_challenges_related_to_treatment\": \"Regular medicine, therapy, travel, and clinical-test costs\"}', NULL, 1, '2026-08-16 18:02:08', '2026-08-16 18:16:12'),
(3, 'Demo Patient - Samiul Islam', '+8801711000003', 'demo.samiul@example.com', 'rejected', 'public', 'Complete demo registration containing every field from the public registration form. Not a real patient.', '{\"age\": \"8\", \"nid\": \"Not applicable\", \"demo\": true, \"nid_2\": \"DEMO-FNID-0003\", \"nid_3\": \"DEMO-MNID-0003\", \"access\": \"Yes\", \"gender\": \"Male\", \"report\": \"Yes\", \"ability\": \"Walks independently\", \"consent\": \"Yes\", \"devices\": \"Standing Frame\", \"gentest\": \"Yes\", \"housing\": \"Own\", \"steroid\": \"Yes\", \"therapy\": \"Physiotherapy\", \"liv_area\": \"Rural\", \"mutation\": \"Point Mutation\", \"insurance\": \"No\", \"contact_no\": \"+8801711000003\", \"occupation\": \"Farmer\", \"res_report\": \"No\", \"attachments\": {\"photo\": {\"url\": \"assets/src/img/patients_3.jpg\", \"demo\": true, \"filename\": \"demo-patient-3.jpg\", \"content_type\": \"image/jpeg\"}, \"genetic_report\": {\"url\": \"assets/src/doc/Treatment-Fact-Sheet-DMD.pdf\", \"demo\": true, \"filename\": \"demo-genetic-report-3.pdf\", \"content_type\": \"application/pdf\"}}, \"blood_group\": \"O+\", \"cardiac_eva\": \"Yes\", \"class_lavel\": \"Class 2\", \"fin_support\": \"Education Support\", \"gene_report\": \"Yes\", \"nationality\": \"Bangladeshi\", \"steroid_use\": \"Deflazacort\", \"fathers_name\": \"Jahidul Islam\", \"mothers_name\": \"Shahana Islam\", \"occupation_2\": \"Homemaker\", \"otherdetails\": \"\", \"breath_report\": \"No\", \"date_of_birth\": \"2018-01-08\", \"email_address\": \"demo.samiul@example.com\", \"cardiac_report\": \"No\", \"diagnosis_type\": \"1\", \"otherdetails_2\": \"\", \"present_address\": \"Demo Road 3, Rajshahi, Bangladesh\", \"age_at_diagnosis\": \"5\", \"date_of_diagnosis\": \"2023-02-15\", \"fathers_education\": \"SSC\", \"hobbies_interests\": \"Cartoons and puzzles\", \"mothers_education\": \"SSC\", \"patient_full_name\": \"Demo Patient - Samiul Islam\", \"permanent_address\": \"Demo Village 3, Rajshahi, Bangladesh\", \"current_medications\": \"Deflazacort, calcium and vitamin D\", \"other_health_issues\": \"Mild muscle weakness and fatigue\", \"birth_certificate_no\": \"DEMO-BC-2026-0003\", \"emergency_contact_no\": \"+8801811000003\", \"emotional_challenges\": \"Occasional anxiety related to mobility limitations\", \"total_family_members\": \"6\", \"family_history_of_dmd\": \"No known family history\", \"monthly_family_income\": \"28000 BDT\", \"duration_of_steroid_use\": \"3 years\", \"age_when_steroid_started\": \"6\", \"inclusive_education_support\": \"School accessibility and flexible attendance support\", \"guardian_relation_with_patient\": \"Father\", \"financial_challenges_related_to_treatment\": \"Regular medicine, therapy, travel, and clinical-test costs\"}', NULL, 1, '2026-08-16 18:02:08', '2026-08-18 12:28:36'),
(4, 'Demo Patient - Rafi Hossain', '+8801711000004', 'demo.rafi@example.com', 'pending', 'public', 'Complete demo registration containing every field from the public registration form. Not a real patient.', '{\"age\": \"10\", \"nid\": \"Not applicable\", \"demo\": true, \"nid_2\": \"DEMO-FNID-0004\", \"nid_3\": \"DEMO-MNID-0004\", \"access\": \"Yes\", \"gender\": \"Male\", \"report\": \"No\", \"ability\": \"Uses wheelchair\", \"consent\": \"Yes\", \"devices\": \"Wheelchair\", \"gentest\": \"Yes\", \"housing\": \"Rented\", \"steroid\": \"Yes\", \"therapy\": \"Hydrotherapy\", \"liv_area\": \"Semi-urban\", \"mutation\": \"Exon Deletion\", \"insurance\": \"No\", \"contact_no\": \"+8801711000004\", \"occupation\": \"Driver\", \"res_report\": \"Yes\", \"attachments\": {\"photo\": {\"url\": \"assets/src/img/p_muntasir_billah.jpg\", \"demo\": true, \"filename\": \"demo-patient-4.jpg\", \"content_type\": \"image/jpeg\"}, \"genetic_report\": {\"url\": \"assets/src/doc/Treatment-Fact-Sheet-DMD.pdf\", \"demo\": true, \"filename\": \"demo-genetic-report-4.pdf\", \"content_type\": \"application/pdf\"}}, \"blood_group\": \"AB+\", \"cardiac_eva\": \"Yes\", \"class_lavel\": \"Home education\", \"fin_support\": \"Wheelchair\", \"gene_report\": \"Yes\", \"nationality\": \"Bangladeshi\", \"steroid_use\": \"Deflazacort\", \"fathers_name\": \"Masud Hossain\", \"mothers_name\": \"Salma Hossain\", \"occupation_2\": \"Homemaker\", \"otherdetails\": \"\", \"breath_report\": \"No\", \"date_of_birth\": \"2015-11-03\", \"email_address\": \"demo.rafi@example.com\", \"cardiac_report\": \"No\", \"diagnosis_type\": \"1\", \"otherdetails_2\": \"\", \"present_address\": \"Demo Road 4, Khulna, Bangladesh\", \"age_at_diagnosis\": \"6\", \"date_of_diagnosis\": \"2022-01-20\", \"fathers_education\": \"HSC\", \"hobbies_interests\": \"Story books\", \"mothers_education\": \"HSC\", \"patient_full_name\": \"Demo Patient - Rafi Hossain\", \"permanent_address\": \"Demo Village 4, Khulna, Bangladesh\", \"current_medications\": \"Deflazacort, calcium and vitamin D\", \"other_health_issues\": \"Mild muscle weakness and fatigue\", \"birth_certificate_no\": \"DEMO-BC-2026-0004\", \"emergency_contact_no\": \"+8801811000004\", \"emotional_challenges\": \"Occasional anxiety related to mobility limitations\", \"total_family_members\": \"7\", \"family_history_of_dmd\": \"No known family history\", \"monthly_family_income\": \"30000 BDT\", \"duration_of_steroid_use\": \"4 years\", \"age_when_steroid_started\": \"7\", \"inclusive_education_support\": \"School accessibility and flexible attendance support\", \"guardian_relation_with_patient\": \"Father\", \"financial_challenges_related_to_treatment\": \"Regular medicine, therapy, travel, and clinical-test costs\"}', NULL, NULL, '2026-08-16 18:02:08', '2026-08-16 18:05:35');

-- --------------------------------------------------------

--
-- Table structure for table `sms_logs`
--

DROP TABLE IF EXISTS `sms_logs`;
CREATE TABLE IF NOT EXISTS `sms_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `registration_id` int DEFAULT NULL,
  `recipient_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `recipient_phone` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `response` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `registration_id` (`registration_id`),
  KEY `ix_sms_logs_id` (`id`),
  KEY `ix_sms_logs_status` (`status`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `sms_logs`
--

INSERT INTO `sms_logs` (`id`, `registration_id`, `recipient_type`, `recipient_phone`, `message`, `provider`, `status`, `response`, `created_at`) VALUES
(1, 6, 'admin', '+8801XXXXXXXXX', 'New DMD registration #6: Codex Test Patient 20260824160136, +8801724160136', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:01:36'),
(2, 6, 'guardian', '+8801724160136', 'DMD Care Bangladesh received registration #6. Status: pending.', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:01:36'),
(3, 7, 'admin', '+8801XXXXXXXXX', 'New DMD registration #7: Codex Bad Email 20260824160217, +8801824160217', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:02:18'),
(4, 7, 'guardian', '+8801824160217', 'DMD Care Bangladesh received registration #7. Status: pending.', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:02:18'),
(5, 8, 'admin', '+8801XXXXXXXXX', 'New DMD registration #8: Codex Multipart Patient 20260824160321, +8801924160321', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:03:22'),
(6, 8, 'guardian', '+8801924160321', 'DMD Care Bangladesh received registration #8. Status: pending.', 'configured-http', 'skipped', 'SMS_API_URL is not configured', '2026-08-24 10:03:22');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_users_email` (`email`),
  KEY `ix_users_id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 'Super Admin', 'info.codecursor@gmail.com', '$2y$12$souwidvyZ4jo/lGtEEGOP.GdgxfzXNkbeNlzAW1zVilRd5tn57owC', 'super_admin', 1, '2026-08-10 07:21:03', '2026-08-24 16:24:31');

-- --------------------------------------------------------

--
-- Table structure for table `visitor_logs`
--

DROP TABLE IF EXISTS `visitor_logs`;
CREATE TABLE IF NOT EXISTS `visitor_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `visitor_key` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_visitor_logs_visitor_key` (`visitor_key`),
  KEY `ix_visitor_logs_created_at` (`created_at`),
  KEY `ix_visitor_logs_id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `visitor_logs`
--

INSERT INTO `visitor_logs` (`id`, `visitor_key`, `path`, `user_agent`, `ip_address`, `created_at`) VALUES
(2, '1786393137125-9d0c07240424', '/index.html', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-10 20:18:57'),
(3, '1786396977425-c4993fc621a2e8', '/health_care_team.html', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-10 21:22:57'),
(4, '1786557505824-4dd7fddbf4af2', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-12 18:12:53'),
(5, '1786901498070-03bc5eb3ae775', '/health_care_team.html', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-16 18:00:05'),
(6, '1786994279522-d00898497cf1b', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-17 19:26:06'),
(7, '1786994279522-d00898497cf1b', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-17 19:29:00'),
(8, '1787029177942-0eebe8f18dd53', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-18 10:37:15'),
(9, '1787076938044-f929f4a8d4e428', '/health_care_team.html', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-18 18:35:17'),
(10, '1787076938044-f929f4a8d4e428', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-18 18:36:32'),
(11, '1787217509165-b5a15d2655ea3', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-20 09:18:29'),
(12, '1787250611815-5648f72e5db948', '/our_partners.html', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-20 18:30:12'),
(13, '1787250611815-5648f72e5db948', '/', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36', '127.0.0.1', '2026-08-20 19:47:09');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
